### ISSUE TITLE
Transparent backgrounds are being output as black

### ISSUE THREAD

**Issue by benmccann** [JonasKruckenberg/imagetools#143]
I'm trying to use `vite-imagetools` in a SvelteKit project, but am having difficulty because the background of my images is turning to black

![Screenshot from 2021-06-16 12-57-25](https://user-images.githubusercontent.com/322311/122284599-997c0e00-cea2-11eb-87f7-dd460802314e.png)

Compare to the live version: https://c3.ventures/

I've created a repo to reproduce this issue: https://github.com/benmccann/vite-imagetools-bug
Run `npm install` followed by `npm run dev`
The entry point is `src/routes/index.svelte`

**Comment by michael0liver** [comment]
@benmccann Would this be because jpeg doesn't support transparency ?

**Comment by benmccann** [comment]
Oh my gosh. This may be one of the dumbest bugs I've ever filed. But I really couldn't figure it out. Thank you so much!!
