### ISSUE TITLE
How to use with typescript?

### ISSUE THREAD

**Issue by matteoturini** [JonasKruckenberg/imagetools#160]
How do I use 'import' with typescript?

**Comment by sprabowo** [comment]
@matteoturini 
just tried this one (might not be the best solution)

```js
// @ts-ignore
import srcsetWebp from '../example.jpg?w=500;700;900;1200&webp&srcset'
```

**Comment by matteoturini** [comment]
> @matteoturini 
> just tried this one (might not be the best solution)
> 
> ```js
> // @ts-ignore
> import srcsetWebp from '../example.jpg?w=500;700;900;1200&webp&srcset'
> ```

No typing. This is not a fix. Maybe make a flag so that you have to do something like this:

```ts
import example from '../example.jpg'
```
Config:
```
images: {
  'example.jpg': 'w=500;700;900;1200&webp&srcset'
}
```

**Comment by jugglingcats** [comment]
You can also create a file, eg. `typings.d.ts` in your project with:

```
declare module "*.jpg?w=500;700;900;1200&webp&srcset"
```

Not ideal if you have a lot of different formats, but...

**Comment by JonasKruckenberg** [comment]
Yeah, there are a lot of less than ideal solutions to this problem, not much we can do from our side. The real fix is to lobby the typescript guys to allow multiple `*` in module declarations or allow search params to occur in any order.
But until then, presets will ease this a bit.

**Comment by matteoturini** [comment]
> Yeah, there are a lot of less than ideal solutions to this problem, not much we can do from our side. The real fix is to lobby the typescript guys to allow multiple `*` in module declarations or allow search params to occur in any order. But until then, presets will ease this a bit.

Yes, TypeScript could do that. But until then, is it possible to make importing with the config as I mentioned before?

**Comment by JonasKruckenberg** [comment]
A config object like you proposed will not be implemented. It's actually the *exact thing* that motivated this project. It'd should be obvious from looking at your source code what transformations are applied to your image instead of it being a declared somewhere else and applied "magically".
However, using the updated `defaultDirectives` you can implement type-able presets:
```ts
imagetools({
   defaultDirectives: id => {
      if (id.searchParams.has('hero')) { // the `hero` directive was set on the image
         return new URLSearchParams('width=1200;900;800&avif&metadata')
      }
      return new URLSearchParams()
   }
})
```

You can then type the preset:
```ts
declare module '*.jpg?hero' {
   const image: Record<string, any>
   export default image
}
```

**Comment by JonasKruckenberg** [comment]
> However, using the updated `defaultDirectives` you can implement type-able presets:
This got released in `vite-imagetools@4.0.0` and `rollup-plugin-imagetools@3.0.0` respectively.
I feel like this provides enough workarounds for the use in typescript so I'll close this for now. Feel free to reopen if the situation changes!

**Comment by matteoturini** [comment]
this is perfect, thank you so much

Em qua., 10 de nov. de 2021 às 08:33, Jonas Kruckenberg <
***@***.***> escreveu:

**Comment by benblazak** [comment]
as another workaround, for anyone else finding this

rather than create a preset without values, i added
```typescript
declare module "*&imagetools" {
  /**
   * actual types
   * - code https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/output-formats.ts
   * - docs https://github.com/JonasKruckenberg/imagetools/blob/main/docs/guide/getting-started.md#metadata
   */
  const out;
  export default out;
}
```
to my `globals.d.ts` (i'm using sveltekit), and then added `&imagetools` to the end of my imports, e.g.
```typescript
import image from "$lib/assets/image.jpg?w=200;400&format=webp;png&meta&imagetools";
```
imagetools seems to happily ignore the extra query parameter.

this is a bit verbose, but i liked it better than not being able to specify values.

also, one could add specific typing this way, e.g. by
```typescript
declare module "*&meta&imagetools" {
  ...
}
```

**Comment by b-lov** [comment]
thats an awesome and creative solution, thanks!

**Comment by gnuion** [comment]
With the plugin configured as follows, the imported image ending with `?gallery` returns an array of two objects.
```ts
imagetools({
  defaultDirectives: (id) => {
    if (id.searchParams.has("gallery")) {
      return new URLSearchParams("w=300;600&format=webp&as=metadata");
    }
    return new URLSearchParams();
  },
}),
```
```ts
import hauseMitTreppen from "@/assets/images/hause-mit-treppen.jpeg?gallery";
console.log(hauseMitTreppen);
```
Output
![image](https://github.com/JonasKruckenberg/imagetools/assets/16549839/f6d85190-7030-46b9-9b77-1746cb8e9b06)



You then can define the type for the values of interest.

```ts
declare module "*?gallery" {
  const images: {
    width: string;
    src: string;
  }[];
  export default images;
}
```
Now, as you can see, you can access the low res image as `hauseMitTreppen[0].src` and high res with `hauseMitTreppen[1].src`

**Comment by albehrens** [comment]
Imagetools can return:
- A string
- An array of strings
- An object
- An array of objects

I have updated my types like this to reflect that. You know best what type of import to use in your application:

```typescript
interface OutputMetadata {
    src: string; // URL of the generated image
    width: number; // Width of the image
    height: number; // Height of the image
    format: string; // Format of the generated image

    // The following options are the same as sharps input options
    space: string; // Name of colour space interpretation
    channels: number; // Number of bands e.g. 3 for sRGB, 4 for CMYK
    density: number; //  Number of pixels per inch
    depth: string; // Name of pixel depth format
    hasAlpha: boolean; // presence of an alpha transparency channel
    hasProfile: boolean; // presence of an embedded ICC profile
    isProgressive: boolean; // indicating whether the image is interlaced using a progressive scan
}

declare module "*&as=metadata&imagetools-gallery" {
    const outputs: Array<OutputMetadata>;
    export default outputs;
}

declare module "*&as=metadata&imagetools" {
    const outputs: OutputMetadata;
    export default outputs;
}

declare module "*&imagetools-gallery" {
    const outputs: Array<string>;
    export default outputs;
}

declare module "*&imagetools" {
    const outputs: string;
    export default outputs;
}
```

**Comment by mturczyn** [comment]
> A config object like you proposed will not be implemented. It's actually the _exact thing_ that motivated this project. It'd should be obvious from looking at your source code what transformations are applied to your image instead of it being a declared somewhere else and applied "magically". However, using the updated `defaultDirectives` you can implement type-able presets:
> 
> imagetools({
>    defaultDirectives: id => {
>       if (id.searchParams.has('hero')) { // the `hero` directive was set on the image
>          return new URLSearchParams('width=1200;900;800&avif&metadata')
>       }
>       return new URLSearchParams()
>    }
> })
> You can then type the preset:
> 
> declare module '*.jpg?hero' {
>    const image: Record<string, any>
>    export default image
> }
> I'm sorry if this is disappointing to you, but _exactly_ the feature you asked for was the annoyance I experienced with the webpack-responsive-loader (they seem to also support url directives now!) and will therefore not be part of this plugin. I know that this type issue is super annoying; everything is a tradeoff however, and I feel that manual typing is still the better DX than "magic image transformation"

I think it should follow format given in import, i.e. below has worked for me, while suggestion above did not:
```
imagetools({
   defaultDirectives: id => {
      if (id.searchParams.has('hero')) { // the `hero` directive was set on the image
         return new URLSearchParams('w=400&format=webp')
      }
      return new URLSearchParams()
   }
})
```
