### ISSUE TITLE
Split off directives into imagetools-core

### ISSUE THREAD

**Issue by JonasKruckenberg** [JonasKruckenberg/imagetools#17]
I feel like vite-imagetools has potential to grow beyond vite and possibly have rollup, webpack, cli, etc. versions.

This is why I'm looking to split off the directives and core logic into it's own repository.

And this issue will keep track of progress towards that goal

## The refactor roadmap
- [x] rename the repository to imagetools
- [x] make in a monorepo
- [x] create core/lib package
- [x] move directives to core
- [x] improve core unit tests
- [x] create vite package
- [ ] update awesome Vite link
- [x] create rollup package
- [ ] add to awesome rollup repo
- [ ] create cli package
- [ ] create server version ?

**Comment by YamiteruXYZ** [comment]
This is an absolutely amazing idea! Sometimes I can't use a framework I like and often those frameworks don't even use vite. It'd be awesome if we could use this library in any framework. I'm afraid that some features might not be available in some of the bundlers or they will have to be patched using other plugins so it might quickly grow out of hands.

**Comment by JonasKruckenberg** [comment]
Yeah it's definitely something to keep an eye out for!
I think a rollup integration should be straightforward as Vite is basically rollup with more quirks (some might even call it features 😄). I don't know enough about Webpack or parcel to make any guesses to how a plugin for those would look like.
