### ISSUE TITLE
`vite-imagetools cannot find image with id "<id>"`

### ISSUE THREAD

**Issue by k4y4k** [JonasKruckenberg/imagetools#207]
## What I did:
```vue
<template lang="pug">

div.flex.flex-row.overflow-hidden(data-testid="rogues-gallery")
  img(v-for="i in Array(3).fill('')" :src="`${moreImage}`").more-image.w-40.m-3.inline

</template>

<script lang="ts">
// @ts-expect-error
import image from '../img/export/man.png?h=250;500'

export default {
  computed: {
    moreImage: () => image,
  },
}
</script>
```

## What I Wanted:

2 images, one `250px` wide and the other `500px`.

## What I Got:

`
vite-imagetools cannot find image with id "99e660ff1a09e8cfe50c4085fd715e2f41d69980," this is likely an internal error
` is printed to the console (and also to the error overlay on the dev server).

any ideas?

**Comment by k4y4k** [comment]
This is absolutely happening every time I want `man.png` and supply >=2 arguments to any query, like `h=300;600` or `format=webp;png`. 

If I `ctrl-c` the dev server and restart it with `vite --force` (e.g. clearing the cache), the error reappears immediately upon auto-reload.

If I `ctrl-c` the dev server and `rm -rf node_modules/.vite` to make sure that vite's cache is gone, the error reappears once again. 

If I disable network cache in Dev Tools and hard reload, it's back.

---

If you say it might be due to HMR, I might try to simplify my (maybe over-engineered 😅) pipelines. Have you ever encountered a conflict with e.g. postcss or scss? or using pug as a template lang for vue? Something like that?

---

I can give you the code, but these are external images fetched in just before build. So they're on disk in my environment, but on CI they're pulled in from another location as I've been politely asked not to share them. 

If I pull some images down from e.g. Unsplash and it still doesn't work, would that work for you re: a reproduction?

**Comment by JonasKruckenberg** [comment]
Hmm that definitely doesn't seem right. You don't have to share anything you're not allowed to, the repo just needs to reproduce the error!

**Comment by k4y4k** [comment]
I ended up just going back to Gatsby 😕

**Comment by HassanZahirnia** [comment]
> `vite-imagetools` generates a bunch of images, as this is an expensive operation it also caches those images by hash. If you do HMR (or some other funky stuff) this can happen as the rendered page and the cache get out of sync. Is this happening reproducibly? And if so can you provide a repro please?

I have the same issue and I'm using HMR (which obviously is a common thing for development these days).
Is there any way around this ? This tool is really fascinating and I would like to use the multi format feature, but this error would prevent using it while developing.

**Comment by akuales** [comment]
@HassanZahirnia did you ever find a fix for it?

**Comment by jrhager84** [comment]
> `vite-imagetools` generates a bunch of images, as this is an expensive operation it also caches those images by hash. If you do HMR (or some other funky stuff) this can happen as the rendered page and the cache get out of sync. Is this happening reproducibly? And if so can you provide a repro please?

How is using HMR (which is pretty much a standard now) considered 'funky stuff?' I'm getting the same error, and it makes development nearly impossible. Is there a way we can just relegate it to the non-dev envs or build/deploy commands?

**Comment by raremiroir** [comment]
Getting the same issue. Does imagetools interfere with other image optimization packages?
I'm trying to switch from Imgix to imagetools, and am wondering if imagetools is trying to take images which were already optimized by Imgix or smth, hence the error?
Just taking a guess

**Comment by staab** [comment]
I'm getting this pretty frequently as well when using the `as` directive.

**Comment by MSSPL-KamalenduGarai** [comment]
The issue has been raised back in 2021 and now it is 2023. The bug is still there. @JonasKruckenberg will you please look into this and suggest fix.

**Comment by benmccann** [comment]
I'd recommend filing a new issue with a reproduction. This issue is two years old and it sounds like the wasn't a way to reproduce it

**Comment by br0wsa** [comment]
I have the same issue

**Comment by geektechniquestudios** [comment]
I also have this issue.
