### ISSUE TITLE
Default directives should be applied before configs are resolved

### ISSUE THREAD

**Issue by Porges** [JonasKruckenberg/imagetools#216]
At the moment it is not possible to do (e.g.) `defaultDirectives: { width: "10;100" }` since this is only applied after the configs have been resolved, and so cannot generate multiple images.

**Comment by Porges** [comment]
Ah, this is basically the same as #139

**Comment by JonasKruckenberg** [comment]
Yeah I'm open to reconsider this, so lets to further discussion over at #139!
