### ISSUE TITLE
Add support for inlined images by respecting the `?inline` suffix

### ISSUE THREAD

**Issue by RafidMuhymin** [JonasKruckenberg/imagetools#253]
Currently, we can't import inlined images using the `?inline` suffix. But it's a necessary feature to have and also the current behavior is breaking a native functionality. So, I think it should be implemented.

**Comment by JonasKruckenberg** [comment]
Yes this has been a heavily requested feature, but my time is really limited at the moment. If you want this feature fast I'd be open to accepting a PR. 
Also what native functionality is currently broken?

**Comment by RafidMuhymin** [comment]
> If you want this feature fast I'd be open to accepting a PR.

I'll try to make a pr when I have some free time

> Also what native functionality is currently broken?

I was talking about the import url suffixes

**Comment by Suyashtnt** [comment]
Any news on this? It would be really nice to have inline images
