### ISSUE TITLE
How to use from css

### ISSUE THREAD

**Issue by theoephraim** [JonasKruckenberg/imagetools#284]
It seems the plugin is not triggered when including images from css. For example, in a vue single file component, I am setting a background image and the original image is getting loaded.

I know vite does process these urls to some degree, but unclear how it interacts with plugins...

```
// ...rest of single file component
<style>
.my-component {
  background: url('./my-component-bg.png?webp');
}
</style>
```

**Comment by JonasKruckenberg** [comment]
Yes, imports are not detected in CSS. This is a limitation on vites part though, this plugin gets applied to all imports that vite detects.
With vue3 you can use the (somewhat new?) [`v-bind`](https://v3.vuejs.org/api/sfc-style.html#state-driven-dynamic-css)` attribute in CSS to bind the url imported in JS.

**Comment by theoephraim** [comment]
Thanks for the quick reply!

Probably worth adding some notes in the docs about this limitation and potential workarounds.

I'll also see if I can find a related issue with vite, as it would definitely make sense to expose assets imported in css to plugins.
