### ISSUE TITLE
Consider moving from yarn to pnpm

### ISSUE THREAD

**Issue by benmccann** [JonasKruckenberg/imagetools#292]
Rollup, Vite, and SvelteKit all use pnpm. It would be easier to test changes to this library in conjunction with those if it used pnpm as well. Is that something you might be open to?

**Comment by JonasKruckenberg** [comment]
Interesting that vite has migrated to pnpm 🤔
I do like the idea, pnpm compares very favorably in the benchmarks I've seen, but I've never used it so far.

**Comment by JonasKruckenberg** [comment]
Monorepo switched to pnpm!

**Comment by benmccann** [comment]
woohoo! that's great!
