### ISSUE TITLE
Upgrade to Sharp 0.29 for WSL support

### ISSUE THREAD

**Issue by benmccann** [JonasKruckenberg/imagetools#294]
The current version of Sharp does not work on WSL, but upgrading to 0.29 seems to fix it (https://github.com/sveltejs/sites/issues/230). We're starting to use imagetools on svelte.dev and kit.svelte.dev and one of the core maintainers uses WSL, so it would be nice to fix this. For now, we're probably just going to use pnpm overrides as a workaround

I took a quick stab at upgrading, but it looks like a few tests fail because a couple of them had saved output that it compared against and the output slightly differed. I guess the saved files would need to be updated to match the new version of Sharp

**Comment by JonasKruckenberg** [comment]
I totally agree. I also tried upgrading a while ago, but the produced images were different depending on the OS (test snapshots produced on macOS would fail on CI servers and vice versa).

My initial idea was to just have different snapshots for each OS, but that is prohibitively expensive in all regards.
What do think would be the best course of action here?

**Comment by benmccann** [comment]
The hard thing about per-OS snapshots is that users can't produce them easily. I don't normally code on Mac or Windows, so would have a tough time producing those snapshots.

Maybe rather than checking the exact snapshot contents we could just check some properties about them? E.g. check that the image produced is between 5k-6k in size. That should hopefully work on any OS even if the file contents were just slightly different

**Comment by JonasKruckenberg** [comment]
I guess that is another issue yeah, though the fixtures in question should rarely change (you wouldn't expect a directive to suddenly produce a different wildly different image after updating).
The problem with checking image properties is that some directives have hard to quantify effects (like blurring for example).

**Comment by JonasKruckenberg** [comment]
So #297 upgrades to sharp 0.29.x, with the downside that I basically disabled snapshots for the failing tests. Of course this is not ideal, but I guess we can rely on sharp to get image formats right.
