### ISSUE TITLE
Allow output format directives in defaultDirectives

### ISSUE THREAD

**Issue by marcustyphoon** [JonasKruckenberg/imagetools#320]
Hello 👋 

My collaborator and I are trying to use vite-imagetools to transition a project from the Gatsby ecosystem. We weren't able to use a `meta` format directive from within the `defaultDirectives` override, as the actual import's parameters are checked for output formats.

I assume allowing this would be as simple as changing `srcURL.searchParams.has(key)` to `directives.has(key)` here:

https://github.com/JonasKruckenberg/imagetools/blob/58eabc941d5270f65e353f4b3466f4d337a109eb/packages/vite/src/index.ts#L97-L106

Is there a reason this isn't permitted, or is this an oversight? Thanks for any info!

(And, before you ask, yes, I can think of ways in which our use of defaultDirectives in some cases rubs up against the spirit of some of the comments in #160, but we aren't able to make use of query parameters with dynamic import vars without hacking the rollup plugin, and I feel fine using defaultDirectives in this spot.)

**Comment by benmccann** [comment]
This has been done:

https://github.com/JonasKruckenberg/imagetools/blob/a5d1fb92b915e6b38925b363203aeed324d709cb/packages/vite/src/index.ts#L99
