### ISSUE TITLE
Why is the behavior of aspect different in different scenarios

### ISSUE THREAD

**Issue by RafidMuhymin** [JonasKruckenberg/imagetools#323]
Why is the behavior of the `aspect` config option in different scenarios? It's not intuitive and it's confusing also. https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/transforms/resize.ts#L60

**Comment by JonasKruckenberg** [comment]
The idea of the `aspect` directive is to resize the source image to fit a given aspect ratio, while removing as little from the original image as possible.

This is why we need to determine which sides to resize based on the source aspect ratio.

**Comment by RafidMuhymin** [comment]
I am not sure if it's only me but this behavior felt very confusing to me. Instead of an image with an incorrect aspect ratio (it's relative), I expected imagetools to return an enlarged image.

**Comment by RafidMuhymin** [comment]
And I had to correct this behavior in `astro-imagetools` as it confused multiple users.
