### ISSUE TITLE
Not resizing images in DEV mode - SvelteKit

### ISSUE THREAD

**Issue by BillBuilt** [JonasKruckenberg/imagetools#325]
Hello,
Having some difficulty getting imagetools to resize properly in dev mode. Works fine in prod mode (`npm run build`). At first I thought it may be browser caching, but clearing the cache, using private mode, using a completely different browser, restaring the PC, etc.... nothing seems to fix it. It's hashing 2 different urls as expected and the metadata object is reporting the size correctly, but when rendered in the brower, it is the full-sized (original) image.

Here is my svelte.config.js:
```
import adapter from '@sveltejs/adapter-auto'
import preprocess from 'svelte-preprocess'
import path from "path"
import { imagetools } from 'vite-imagetools'


/** @type {import('@sveltejs/kit').Config} */
const config = {
	// Consult https://github.com/sveltejs/svelte-preprocess
	// for more information about preprocessors
	preprocess: preprocess(),

	kit: {
		adapter: adapter(),
		vite: {
			resolve: {
				alias: {
					$models: path.resolve('./src/models'),
					$lib: path.resolve('./src/lib'),
					$comp: path.resolve('./src/components'),
				}
			},
			ssr: {
				noExternal: ['@fortawesome/free-brands-svg-icons', '@fortawesome/free-regular-svg-icons', '@fortawesome/free-solid-svg-icons']
			},
			plugins: [imagetools({force: true})]
		}
	}
}

export default config
```

The url for the import: `import image from '$lib/assets/stock/1_full.jpg?w=300;1920&metadata'`

The img tag: `<img src={image[0].src}/>`

The metadata: 
```
 [
    {
      format: 'jpeg',
      width: 300,
      height: 200,
      space: 'srgb',
      channels: 3,
      depth: 'uchar',
      density: 300,
      chromaSubsampling: '4:4:4',
      isProgressive: false,
      hasProfile: false,
      hasAlpha: false,
      src: '/@imagetools/332a3a67d70f998a8a8c26556f9e60ab9b1a7fff'
    },
    {
      format: 'jpeg',
      width: 1920,
      height: 1280,
      space: 'srgb',
      channels: 3,
      depth: 'uchar',
      density: 300,
      chromaSubsampling: '4:4:4',
      isProgressive: false,
      hasProfile: false,
      hasAlpha: false,
      src: '/@imagetools/b9f621074cb509f2464a3cb483ccc4d9d40601a2'
    }
  ],
```

And attached is a screenshot of my browser's inspection console that shows the image with src: `'/@imagetools/332a3a67d70f998a8a8c26556f9e60ab9b1a7fff'` being displayed at the full resolution as opposed to the 300x200

<img width="602" alt="Screen Shot 2022-04-15 at 1 41 43 PM" src="https://user-images.githubusercontent.com/28831382/163604817-708a46dc-cc95-4cff-9fd5-31ed60884c26.png">

Not sure what could be happening here....

**Comment by rafaucau** [comment]
It doesn't work at all in dev mode for me
![image](https://user-images.githubusercontent.com/25438601/166164643-6b61eea2-445c-4c29-b274-5a6c5b453f75.png)

**Comment by salimranainfo** [comment]
Same problem here. Its not working in dev mode :-(

**Comment by jeffreyvanhees** [comment]
Same here, using Vue 3 only. `npx vite build --config vite.config.js` is going fine but with `npx vite --config vite.config.js` (dev) it generates non-existing URL's for images:

```
<img src="/@imagetools/9c4de2da35107fd57d6053535d0a4b10ee19ed8d" class="hidden md:block" height="80" width="80" alt="">```

**Comment by benmccann** [comment]
I haven't checked the sizing, but the images are definitely showing up in dev mode for me with SvelteKit. You can see it working in dev mode on the SvelteKit and Svelte sites:
- https://github.com/sveltejs/kit/tree/master/sites/kit.svelte.dev
- https://github.com/sveltejs/sites/tree/master/sites/svelte.dev

**Comment by benmccann** [comment]
If you're still having an issue with this, please share a repository that reproduces the issue. Otherwise I'll close this

**Comment by benmccann** [comment]
Closing this given the lack of response
