### ISSUE TITLE
Animated Webp does not animate 

### ISSUE THREAD

**Issue by gianpesto** [JonasKruckenberg/imagetools#330]
Hej,
i'm needing an animated WebP and turn it into different formats with a jpg fallback:
``
import AnimatedVisual from "~/assets/images/whateverwebp?width=1200;1920&format=avif;jpg&metadata";
``
unfortunatly the transformed image does not animate anymore although it seems to have gotten the pages right:

``
[
  {
    "format": "avif",
    "width": 1200,
    "height": 210.9375,
    "space": "srgb",
    "channels": 4,
    "depth": "uchar",
    "isProgressive": false,
    "pages": 25,
    "pageHeight": 675,
    "loop": 0,
    "delay": [10,... ],
    "hasProfile": false,
    "hasAlpha": true,
    "aspect": 1.7777777777777777,
    "src": "/@imagetools/dd2e2ce2205f7914a916132d21875001c72085ba"
  },
...
``

any ideas what might be wrong with this?

**Comment by JonasKruckenberg** [comment]
From the [Sharp documentation](https://sharp.pixelplumbing.com/api-output#avif):

> AVIF image sequences are not supported.

So this is a limitation with the upstream library, please open an issue with them if you need animated avif images. Otherwise you'll have to use gifs or stick to wep
