### ISSUE TITLE
Update dependency `sharp` to ^0.30.5

### ISSUE THREAD

**Issue by hofrob** [JonasKruckenberg/imagetools#331]
There was a [vulnerability](https://github.com/advisories/GHSA-gp95-ppv5-3jc5) in the sharp package. According to the advisory, it was fixed in 0.30.5. Current version is 0.30.6.

Please update your dependency if possible, so that other projects (like [astro-imagetools](https://www.npmjs.com/package/astro-imagetools)) that are relying on this package are not affected anymore.

Thanks in advance!

**Comment by JonasKruckenberg** [comment]
Will publish a new version of all packages with updated dependency versions in like 20 minutes

**Comment by JonasKruckenberg** [comment]
published as `imagetools-core@3.0.3`, `vite-imagetools@4.0.4` and `rollup-plugin-imagetools@3.0.5` respectively

**Comment by hofrob** [comment]
Thank you for the fast response!
