### ISSUE TITLE
defaultDirective option doesn't work

### ISSUE THREAD

**Issue by winston0410** [JonasKruckenberg/imagetools#355]
Tried to use the default directive with SvelteKit, but seems like the `URLSearchParams` there are not merged:

```javascript
				imagetools({
					defaultDirectives: (url) => {
						return new URLSearchParams({
							metadata: ""
						})
					}
				}),
```

This should add `metadata` as query string to all URL, but it doesn't work.

**Comment by JonasKruckenberg** [comment]
This has been fixed by #357 and will be included in the next release
