### ISSUE TITLE
Docs: install / basic usage description in readme, define defaults

### ISSUE THREAD

**Issue by MentalGear** [JonasKruckenberg/imagetools#362]
Please put  install and usage notes directly in the main readme on github.

Also, as someone who would like to serve modern or legacy images automatically based on the user, I would like to know if the default imagetools configuration does this , or if I have to specify for each image ?webp&jpg, etc. I couldn't find anything on this.

**Comment by JonasKruckenberg** [comment]
> Please put install and usage notes directly in the main readme on github.

This repo is a monorepo that contains multiple packages, all with their own installation and usage instructions. You should refer to the Readme of the package you're interested in for details.

> Also, as someone who would like to serve modern or legacy images automatically based on the user, I would like to know if the default imagetools configuration does this , or if I have to specify for each image ?webp&jpg, etc. I couldn't find anything on this.

Check out the [`defaultDirectives` (vite)](https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite#defaultdirectives) or [`defaultDirectives` (rollup)](https://github.com/JonasKruckenberg/imagetools/tree/main/packages/rollup#defaultdirectives) option. It allows you to apply directives based on the image url.
