### ISSUE TITLE
Path escaping problem on Windows

### ISSUE THREAD

**Issue by lihe07** [JonasKruckenberg/imagetools#364]
When I'm trying to import an image url: `import bg from '../assets/bg.jpg?webp'`

In vite dev server, my browser is performing this request, which is not found: 
`GET | http://localhost:3000/@imagetools%EF%BF%BDdc92fdc26e483ca9f1c55f19cfa0723b10`

I tried to console.log the variable `bg`. Note the backslashes here. I believe these caused the problem.

`\@imagetools\bf6348dc92fdc26e483ca9f1c55f19cfa0723b10`

And when I replaced these backslashes, the problem goes away.

`bg.replace(/\\/gi, '/')`

> Note: This problem doesn't happen in built version

**Comment by JonasKruckenberg** [comment]
If you have the time, could you try out this commit b84387434d60e7ea53c6fb806134e8f1d24e6243 directly from git? I just tested with my windows VM and everything seems to work fine with the example app. But you should test with your app too.

**Comment by simonbuchan** [comment]
@JonasKruckenberg that fixes it for me!

**Comment by JonasKruckenberg** [comment]
Awesome thanks for checking 😁 I'll cut a release once I got the upgrade to vite v3 done!

**Comment by JonasKruckenberg** [comment]
Releases for both plugins have been published to npm now!
