### ISSUE TITLE
Bug: Paths are relative instead of absolute

### ISSUE THREAD

**Issue by Amerlander** [JonasKruckenberg/imagetools#367]
I've just upgraded a project from sveltekit 3xx to 4xx. The formerly absolute paths created by imagetools are now relative (to `/`) and therefore not working on any subpage.

```
<script>
	import Img from './image.jpg?webp&meta'
</script>

{Img.src}
```
will result in
```
./_app/immutable/assets/image-a774634e.webp
```

In dev mode everything works, but as soon as I build the path is wrong.
Before the upgrade the result was `/_app/immutable/assets/image-a774634e.webp` for `{Img.src}`. So without the leading `.`.

# Repro
- clone https://github.com/Amerlander/image-import-test and `npm i`, `npm run build`: 
- Open `/about` and check the sources below the headline.
- Theres also a import without using imagetools which still produces the right path

**Comment by benmccann** [comment]
This sounds unlikely to be related to `imagetools` and more likely related to https://github.com/sveltejs/kit/pull/4250

**Comment by JonasKruckenberg** [comment]
I will  close this issue then, seems indeed not like something imagetools can change

**Comment by benmccann** [comment]
This may be from `imagetools` after all. Can you check if https://github.com/JonasKruckenberg/imagetools/pull/400 would fix the issue you're facing?
