### ISSUE TITLE
TypeScript error when using width parameter

### ISSUE THREAD

**Issue by kevinrenskers** [JonasKruckenberg/imagetools#371]
This works fine:

```
import MyImage from "$lib/assets/my-image.png";
```

But this gives a TypeScript error:

```
import MyImage from "$lib/assets/my-image.png?width=570";
// Cannot find module '$lib/assets/my-image.png?width=570' or its corresponding type declarations.
```

Mind you the actual image works fine, nothing is broken, but I'd really like to have zero TS errors in my project. Any idea on how to solve this?

**Comment by romanran** [comment]
[#160](https://github.com/JonasKruckenberg/imagetools/issues/160)

**Comment by kevinrenskers** [comment]
Thanks, https://github.com/JonasKruckenberg/imagetools/issues/160#issuecomment-1009292026 is a fine workaround.
