### ISSUE TITLE
Restore `main`, `module`, and `types`

### ISSUE THREAD

**Issue by scheatkode** [JonasKruckenberg/imagetools#416]
The `exports` field is still fairly new for Typescript users, most of whom still have `"moduleResolution": "node"` in their `tsconfig.json`s. Such is the case of this repo as well.

The latest PR #404 from @benmccann removed the `main`, `module`, and `types` fields which node relies on for its module resolution.

```
src/blur/index.ts(1,29): error TS2307: Cannot find module 'imagetools-core' or its corresponding type declarations.
src/blur/index.ts(4,39): error TS2307: Cannot find module 'imagetools-core' or its corresponding type declarations.
src/blur/index.ts(42,33): error TS7006: Parameter 'config' implicitly has an 'any' type.
error Command failed with exit code 1.

```

AFAIK, the aforementioned fields can coexist with the `exports` fields.

**Comment by JonasKruckenberg** [comment]
Hotfixes `imagetools-core@3.2.3`, `vite-imagetools@4.0.11` and `rollup-plugin-imagetools@3.0.12` are published now
