### ISSUE TITLE
Is it necessary to call image.withMetadata()?

### ISSUE THREAD

**Issue by brendon** [JonasKruckenberg/imagetools#432]
I've been doing a super deep dive creating a transform that compresses images with `tinify` (TinyPNG etc...). Part of this process is to replace the sharp stream with what it returned from `tinify`. I notice below you are calling `image.withMetadata()` but I'm not sure this mutates the `image` at all? It seems to be a redundant call.

https://github.com/JonasKruckenberg/imagetools/blob/b493224f07f796430029c49b4265d0a5d3b44326/packages/core/src/lib/apply-transforms.ts#L20

Just double-checking though as if it is necessary to refresh the metadata then I'll need to do that in my transform too.

Ideally I would have liked to return a completely new instance of `sharp` from my transform but the way the `image[METADATA]` thing is written makes it difficult to copy the metadata from the original image. I suppose I could loop through all the `metadata()` and add it one at a time with `setMetadata()` :)

**Comment by brendon** [comment]
This is my semi-final solution for the transform:

```
import { imagetools } from 'vite-imagetools'
import { setMetadata } from 'imagetools-core'
import tinify from 'tinify'
tinify.key = 'XXXXXXXXXXXXXXXXXXXXXXXX'

const imageRegex = /\.(png|jpe?g|webp)$/

export default () => ({
  name: 'tinyify',
  ...imagetools({
    defaultDirectives(url) {
      if (imageRegex.test(url)) {
        return new URLSearchParams('tinify')
      } else {
        return new URLSearchParams
      }
    },
    extendTransforms(builtins) { return [tinifyDirective, ...builtins] }
  })
})

function tinifyDirective(config) {
  if (!('tinify' in config)) { return }

  return async function(image) {
    const imageBuffer = await image.withMetadata().toBuffer()
    const tinyImageBuffer = await tinify.fromBuffer(imageBuffer).toBuffer()
    image.options.bufferIn = tinyImageBuffer

    setMetadata(image, 'tinify', true)
    return image
  }
}
```

Just need to add caching for already compressed assets :)

**Comment by sawyerclick** [comment]
`.withMetadata()` is a [Sharp method](https://sharp.pixelplumbing.com/api-output#withmetadata) and is unrelated to the internal metadata object. It's needed so that Sharp knows to include the original file's metadata, otherwise it's stripped

**Comment by brendon** [comment]
Thanks for that :) Sadly I ended up not being able to use this for non-related reasons but it worked well :) Hope it helps someone else :)
