### ISSUE TITLE
Picture directive not creating multiple formats

### ISSUE THREAD

**Issue by chrskerr** [JonasKruckenberg/imagetools#448]
Hello!

I am using the following string to import an image, and I get an empty array of sources from the import. 

```
import orgDndImage from '$lib/images/org-dnd.png?w=250&webp;png&picture';
```

When I add more sizes, eg,

```
import orgDndImage from '$lib/images/org-dnd.png?w=250;201;202&webp;png&picture';
```

I get the following object back

```
{
	fallback: {src: "/@imagetools/6dd88a27e35e037408f712d5077916b9d9165e00", w: 250, h: 179.36802973977694},
	sources: {
		png: [
			{src: "/@imagetools/6dd88a27e35e037408f712d5077916b9d9165e00", w: 250},
			{src: "/@imagetools/7e10ce3fa4abcc26489e8604f5b847746fd66ca8", w: 201},
			{src: "/@imagetools/114cdf8bbdf51fd1036cc9bcc1a4ba6426156305", w: 202},
		],
	},
}
```

I have taken this from the docs as the correct import string, how do I create additional source formats?

I am using sveltekit, and am importing the plugin as follows. This is being run in dev mode.

```
// vite.config.js

{
	...
	plugins: [imagetools(), sveltekit()],
}
``` 

Thanks!

**Comment by Amorites** [comment]
I have met the same problem, and adding a `format=` solved it.

Just try `import orgDndImage from '$lib/images/org-dnd.png?w=250&format=webp;png&picture';`

**Comment by chrskerr** [comment]
Thank you @Amorites I've just tried this and it seems to only give the web format now

![Screenshot 2022-12-15 at 5 41 07 pm](https://user-images.githubusercontent.com/10432093/207801248-b2b8abb5-5728-4473-aaa2-d71aa1aa2093.png)

**Comment by chrskerr** [comment]
If I swap png to be the first format (eg `import orgDndImage from '$lib/images/org-dnd.png?w=250&format=png;webp&picture';`) then I get the below

![Screenshot 2022-12-15 at 5 42 56 pm](https://user-images.githubusercontent.com/10432093/207801600-28051e9e-9550-43cd-adae-853efb07c355.png)

**Comment by sawyerclick** [comment]
This is an issue with your syntax and not with the picture directive. 

You cannot use multiple shorthand directives, per the [docs](https://github.com/JonasKruckenberg/imagetools/blob/main/docs/directives.md#format). Use `format=webp;png` instead.

**Comment by JonasKruckenberg** [comment]
I honestly think this behavior (not being able to specify multiple shorthands) and we might remove shorthand's entirely for this reason. Bit @sawyerclick answer stands correct.

**Comment by chrskerr** [comment]
> If I swap png to be the first format (eg `import orgDndImage from '$lib/images/org-dnd.png?w=250&format=png;webp&picture';`) then I get the below
> 
> ![Screenshot 2022-12-15 at 5 42 56 pm](https://user-images.githubusercontent.com/10432093/207801600-28051e9e-9550-43cd-adae-853efb07c355.png)

Is this correct behaviour though? Not shorthand, multiple formats, and only getting a single result

**Comment by sawyerclick** [comment]
This is correct still as your `fallback` image is the first variant. your `sources` includes your other options.

In other words, you need an image to be the fallback. Your directive here returns two images, so one is a fallback and the other is a part of your sources.

Order your format directives (and others) to match your preference. I typically do `format=png;webp;avif`
