### ISSUE TITLE
Replace image with same file name does not work in dev mode

### ISSUE THREAD

**Issue by Amorites** [JonasKruckenberg/imagetools#449]
Now I need to restart vite and clear the browser cache to get the image to change successfully.

Maybe we should add `mtimeMs` stat info in the file id here:

https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/util.ts#L9

**Comment by tienpv222** [comment]
A workaround is to attach a custom config (such as file hash, or `time` as you suggested). Example:

```ts
// vite.config.ts
imagetools({
  defaultDirectives(url) {
    const buffer = readFileSync(url.pathname);
    const hash = createHash("sha1").update(buffer).digest("hex");

    return new URLSearchParams({ hash });
  },
}),
```

You might also need to disable `sharp` caching, since the file path won't change.

```ts
import sharp from "sharp";
sharp.cache(false);
```
