### ISSUE TITLE
basePath issue when provided url

### ISSUE THREAD

**Issue by dschewchenko** [JonasKruckenberg/imagetools#500]
Hello. We have Module Federation setup, and for local development we may to set **base** path like http://localhost:3010
For now it parses an url as path, that results in this
"http:/localhost:8510/@imagetools/6c73c055dfe50565c381b711109e5d06f30152e6"
protocol broken, without double slash

Could you please fix this?

**Comment by benmccann** [comment]
This is not a priority for me and not something I'm likely to address, but I will review and merge a PR if you'd like to send a fix

**Comment by dschewchenko** [comment]
Thank you!
