### ISSUE TITLE
Unexpected metadata results after image import & transformation

### ISSUE THREAD

**Issue by nick-vincent** [JonasKruckenberg/imagetools#510]
Hello there! 👋

I've set up a [barebones SvelteKit repo](https://github.com/nick-vincent/vite-imagetools-metadata-example) to demonstrate some unexpected metadata results using `vite-imagetools`.

In case you have trouble running it, here is a screenshot from the demo:

<img width="589" alt="image" src="https://user-images.githubusercontent.com/31055081/218856793-235ea886-c9be-469d-8972-0ea79a48d880.png">

Basically, I'm using `vite-imagetools` to import a 1600x900 PNG image and resize it to fit inside 480x480.

The image is correctly converted and resized! However, the metadata returned is not what I'd expect:

```
Image.aspect: undefined (should be 1.778 or 16:9)
Image.height: 480 (should be 270)
Image.width: 480 (should be 480)
```

As you can see, the `aspect` ratio is not returned at all. Additionally, I'd expect the `height` and `width` metadata to reflect the final dimensions of the processed image, not the `h` & `w` values passed via the query param.

Is this user error on my part, or is this returning incorrect metadata? And am I posting this issue in the right place? 🤔 

Thanks in advance for looking into this, and let me know if i can help further diagnose!

**Comment by nick-vincent** [comment]
Hi again @JonasKruckenberg!

I was looking at [this code](https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/transforms/resize.ts#L99-L101) and it does seem like the intention is to return the final metadata values of the transformed image:

```js
    setMetadata(image, 'height', finalHeight)
    setMetadata(image, 'width', finalWidth)
    setMetadata(image, 'aspect', finalAspect)
```

I tried downgrading `imagetools-core` to v3.2.3 which does fix the aspect ratio (but not the computed width & height): 

<img width="605" alt="image" src="https://user-images.githubusercontent.com/31055081/229323423-b10f04d7-3e0f-46ef-a0fb-b38f6a591878.png">

So it seems something broke in v3.3.0, maybe in @sawyerclick's [PR](https://github.com/JonasKruckenberg/imagetools/pull/461) to add `withoutEnlargment` & `withoutReduction`?

**Comment by sawyerclick** [comment]
Thanks for flagging! I'll check out the aspect ratio issue promptly.

On the width and height, are you certain those stem from the withoutEnlargement and withoutReduction additions? If so, I can investigate.

**Comment by nick-vincent** [comment]
> On the width and height, are you certain those stem from the withoutEnlargement and withoutReduction additions?

@sawyerclick Actually no, it doesn't seem those changed with your PR! They were still incorrect (?) previously in 3.2.3.

**Comment by nick-vincent** [comment]
I dug into this a bit more...

There is an additional case not being handled in [`resizeTransform`](https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/transforms/resize.ts#L58): If both `width` AND `height` are given, but no `aspect`.

This case is a bit complicated, because the `fit` needs to be considered and possibly used to recalculate all the values.

**Comment by nick-vincent** [comment]
I went ahead and drafted [a PR here](https://github.com/JonasKruckenberg/imagetools/pull/524) that I believe addresses these bugs.

I couldn't find anything in [resize.spec.ts](https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/transforms/__tests__/resize.spec.ts) testing the metadata, any pointers there?
