### ISSUE TITLE
Use custom query on a dynamic import

### ISSUE THREAD

**Issue by AaronNBrock** [JonasKruckenberg/imagetools#538]
Is it possible to use Glob Import's [Custom Queries](https://vitejs.dev/guide/features.html#custom-queries) with a dynamic import?

Something akin to:

```javascript
import(`../../cat01.jpg?run`, {
  query: { some: 'query' }
})
```

**Comment by benmccann** [comment]
This would be a question for Vite. We don't do anything special with regards to imports, etc.

**Comment by benmccann** [comment]
I just added `import.meta.glob` to the docs and examples and verified that it works with `query`. I'm not exactly sure what you're trying to do, but at the very least you could `import.meta.glob` a single image with `query`
