### ISSUE TITLE
?webp shorthand still works on 5.0.4

### ISSUE THREAD

**Issue by khromov** [JonasKruckenberg/imagetools#565]
I have imports like this:

```
import ribbonImage from '$lib/assets/ribbon.png?webp';
```

After updating to 5.0.4, I can still use these shorthands, even though in the changelog it said they were removed:
https://github.com/JonasKruckenberg/imagetools/blob/main/packages/vite/CHANGELOG.md

```
# npm ls vite-imagetools
/project
└── vite-imagetools@5.0.4
```

**Comment by benmccann** [comment]
Hmm, I definitely wouldn't expect it to work. The code was removed in https://github.com/JonasKruckenberg/imagetools/pull/537

**Comment by benmccann** [comment]
Are you sure it's actually generating a webp image? I just tried:
```
<img src="./_images/closefactor.png?webp" alt="CloseFactor" />
```

And it gave me back a png:
![Screenshot from 2023-10-17 11-14-20](https://github.com/JonasKruckenberg/imagetools/assets/322311/eb431694-e237-4ace-9dfb-d01dae6a15e1)
