### ISSUE TITLE
Cropping support

### ISSUE THREAD

**Issue by ThePeach** [JonasKruckenberg/imagetools#574]
Hello, and thank you very much for this library.
I've been using it quite a bit, and I feel I'm currently missing one bit of functionality: cropping.
Two of the most basic examples I can provide are:
1. being able to generate fixed-sized images for social media purposes. 
2. being able to generate a cropped-up version of an image to create thumbnails (this is sometimes a non-problem since CSS helps a lot).

Thanks!

**Comment by mathiasbosman** [comment]
Hey @ThePeach you can pass widht and height with the `w` and `h` parameters.

For example:

```javascript
import foo_bar from "images/foobar.jpeg?w=100&h=100"
```

after which you can use `foo_bar` as you image's source.

**Comment by JonasKruckenberg** [comment]
Closing this as completed. Thanks @mathiasbosman for responding so helpfully 👍🏻
