### ISSUE TITLE
Query strings don't work in dynamic imports with template literals containing variables

### ISSUE THREAD

**Issue by refact0r** [JonasKruckenberg/imagetools#575]
I am working on a static Sveltekit site.
When I dynamically import an image with
```js
const module = await import(`$lib/images/${name}.jpg?w=400`)
```
I get
![image](https://github.com/JonasKruckenberg/imagetools/assets/34758569/ada88ec4-8712-47e5-9b24-756e81c36d6d)
It seems to be applying my defaultDirectives:
```js
return new URLSearchParams({
    format: `avif;jpg`,
    w: '2000;1000;500',
    as: 'picture'
})
```
but the actual directives in the URL don't work.

**Comment by ZakkProjects** [comment]
Probably not the best possible solution, 

You can always make defaultDirectives more specific using conditionals as specified in [docs under options](https://github.com/JonasKruckenberg/imagetools/tree/main/packages/vite#options):

```
    imagetools({
      defaultDirectives: (url) => {
        if (url.searchParams.has('spotify')) {
          return new URLSearchParams({
            tint: 'ffaa22'
          })
        }
        return new URLSearchParams()
      }
    })
```
and instead of long string you can use it as your "own" directive.

You can also use more complicated conditions.

I solved it by just appending the rest at the end.
```
		imagetools({
			defaultDirectives: (url: URL) => {
				const extension = url.pathname.substring(url.pathname.lastIndexOf('.') + 1);
				if (['png', 'jpg', 'jpeg'].includes(extension)) {
					return new URLSearchParams(
						'format=avif;webp;' + extension + '&as=picture&w=2000;1000;500' + url.searchParams
					);
				}
				return new URLSearchParams();
			}
		}),
```

But i can also imagine ignoring all defaults by using
```
		imagetools({
			defaultDirectives: (url: URL) => {
				if (url.searchParams.has('custom')) {
					return url.searchParams;
				}
				return new URLSearchParams();
			}
		}),
```

**Comment by refact0r** [comment]
Thanks, this works as a solution. 

But it is still quite weird that with normal imports the default directives are overwritten, but with dynamic imports they are not (at least this was the case when I submitted this issue, I have not tried to reproduce since then).

**Comment by JonasKruckenberg** [comment]
It would be interesting to see if this is still the case, I remember that dynamic imports are behaving slightly differently to regular imports in vite.

**Comment by benmccann** [comment]
This seems to work for me

![Screenshot from 2023-09-21 16-19-41](https://github.com/JonasKruckenberg/imagetools/assets/322311/c9224aa5-30fd-4419-afc0-8eb30befc4b9)

Can anyone provide a project that reproduces this? Otherwise I'll assume it works and close the issue

**Comment by refact0r** [comment]
@benmccann I think you misunderstood, the problem is that static imports can override the defaultDirectives defined in vite config, but dynamic imports cannot. 

I can still reproduce the issue. (repo: https://github.com/refact0r/imagetools-575)

```js
imagetools({
	defaultDirectives: () => {
		return new URLSearchParams({
			blur: '10'
		});
	}
}),
```

```html
<script>
	import { onMount } from 'svelte';
	import static_image from '../../static/favicon.png?blur=1';

	let dynamic_image;
	let name = 'favicon';

	onMount(async () => {
		dynamic_image = (await import(`../../static/${name}.png?blur=1`)).default;
	});
</script>

<h1>Welcome to SvelteKit</h1>
<p>Visit <a href="https://kit.svelte.dev">kit.svelte.dev</a> to read the documentation</p>

<p>static import</p>
<img src={static_image} alt="Svelte logo" />

<p>dynamic import</p>
<img src={dynamic_image} alt="Svelte logo" />
```

![image](https://github.com/JonasKruckenberg/imagetools/assets/34758569/6f31e99c-eddd-4fbf-9cc4-b772c20dc928)

**Comment by benmccann** [comment]
Ok, so there are more parts to this. It's not that you override a defaultDirective, but it's that you use a template literal that has a variable together with a query string. This one will have to be addressed in Vite: https://github.com/vitejs/vite/issues/14449

I'll note that I also hit https://github.com/vitejs/vite/issues/14101 while debugging this

**Comment by refact0r** [comment]
Ah, that makes sense.

**Comment by benmccann** [comment]
This will be fixed in Vite 5. Thanks to @Dunqing for the fix!
