### ISSUE TITLE
Build and build -w output differs

### ISSUE THREAD

**Issue by draotth** [JonasKruckenberg/imagetools#594]
### Problem
The outputted images for `vite build -w` have the `/@imagetools/*` reference, which consumers of my library cannot interpret or find.

### My workaround
Running `build` (no watch) with chokidar to publish updates to calc locally works, but has it's own problems (e.g. production build, no HMR, etc).

I statically copy the images from the npm package (I'm using chokidar/yalc to publish the changes when the `dist` folder of the Component Lib changes).

### Possible solutions
1. Change (or allow configuration of) imagetools to output 
2. Let me know the location of the `/@imagetools` files, and I can try to see if I can manually copy those in dev mode.

**Comment by benmccann** [comment]
That's probably coming from this line: https://github.com/JonasKruckenberg/imagetools/blob/76ccb9127e783bb0fcd3cdd9ada2efc634d74f34/packages/vite/src/index.ts#L113

That line should probably be updated to check if we're in build mode or dev mode instead. I don't know that I'll get to this for awhile, but a PR would be welcome. I can review and merge quickly if you'd like to take stab at it

**Comment by draotth** [comment]
Switched to use `viteConfig.isProduction`, which has the following values:
1. `vite build` - `true`
2. `vite build -w` - `true`
3. `vite  dev` - `false`

However, the unit tests using the Javascript API seem to have this as always false, even if you set `mode: 'production'`

This, of course, breaks the output paths for all the tests. Any thoughts off-hand?

**Comment by draotth** [comment]
Oh, the unit tests are always run in `NODE_ENV=development` and therefore so is the Vite JavaScript build process.

I'll try and see if using a separate node process for this is possible.

**Comment by draotth** [comment]
This is because NODE_ENV is set while unit testing to `production`.

This leads me to think that `isProduction` is less reliable for this and perhaps other unknown reasons.

`(viteConfig.command !== 'build')` seems much more reliable for the use case here.

**Comment by draotth** [comment]
Hey! Do I need permission to push my fix branch?

**Comment by benmccann** [comment]
Thank you for the fix! https://github.com/JonasKruckenberg/imagetools/pull/595

**Comment by draotth** [comment]
Thanks for the fast responses!
