### ISSUE TITLE
manifest.json is generated incorrectly

### ISSUE THREAD

**Issue by honzahana** [JonasKruckenberg/imagetools#598]
Hi folks, thanks for your work. I came across a problem that probably hasn't been discussed here before.

When I import an image for processing in imagetools, it is misinterpreted in the manifest.json that is generated by Vite.js. It is then difficult/impossible to process the files in the backend.

Enable `manifest.json` in `vite.config.js`:

```
import { defineConfig } from 'vite'
import { svelte } from '@sveltejs/vite-plugin-svelte'
import viteCompression from 'vite-plugin-compression';
import { imagetools } from 'vite-imagetools'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    viteCompression({
      algorithm:'brotliCompress',
      filter:/\.(js|json|css|svg)$/i
    }),
    imagetools(),
    svelte()
  ],
  build: {
    manifest: true,
  }
})
```

Import image to `main.js`:

```
import './app.css'
import './img/unsplash.jpg?w=400&h=900&format=webp'
import './img/unsplash.jpg?w=400&format=webp'
import './img/side.svg'
```

I have imported two identical images, both to be converted to a different result.

The result in `manifest.json` is:

```
{
  "src/img/side.svg": {
    "file": "assets/side-13b090e5.svg",
    "src": "src/img/side.svg"
  },
  "src/main.css": {
    "file": "assets/main-3a88ba9f.css",
    "src": "src/main.css"
  },
  "src/main.js": {
    "css": [
      "assets/main-3a88ba9f.css"
    ],
    "file": "assets/main-20620a56.js",
    "isEntry": true,
    "src": "src/main.js"
  },
  "unsplash.webp": {  //            <------- this is wrong
    "file": "assets/unsplash-68ec0176.webp",
    "src": "unsplash.webp"
  }
}
```

And there were two problems:

1. `manifest.json` does not **contain the path** and the **original name of the image is wrong** (it should be `unsplash.jpg`)
2. the exported image is only there once, **instead of twice**.

**Comment by benmccann** [comment]
> the exported image is only there once, instead of twice.

I'm not sure how we'd put it twice. It'd duplicate the key. Unless the value can be an array?

**Comment by benmccann** [comment]
@honzahana please file this issue in the Vite issue tracker. Vite is responsible for generating the manifest and there's unfortunately nothing we can do about it in `vite-imagetools`
