### ISSUE TITLE
Renaming picture fallback to img is not reflected in the document

### ISSUE THREAD

**Issue by iicdii** [JonasKruckenberg/imagetools#609]
Picutre's `fallback` property was renamed to `img` in 4.0.0

https://github.com/JonasKruckenberg/imagetools/blob/22f6de60fd7f2805015bd60c970e4a1d1054733f/packages/core/CHANGELOG.md?plain=1#L45

But it doesn't reflected in the document, which confuses

https://github.com/JonasKruckenberg/imagetools/blob/22f6de60fd7f2805015bd60c970e4a1d1054733f/docs/interfaces/vite_src.Picture.md?plain=1#L13

https://github.com/JonasKruckenberg/imagetools/blob/22f6de60fd7f2805015bd60c970e4a1d1054733f/docs/directives.md?plain=1#L437

**Comment by benmccann** [comment]
fixed
