### ISSUE TITLE
more than one width not working in sveltekit app...

### ISSUE THREAD

**Issue by rchrdnsh** [JonasKruckenberg/imagetools#67]
So, gotz me an image, like so, imported into a svelte component from an aliased relative path:

```js
import image from '$images/arrow-event-factory-1920x1200.jpg?width=480'
```

...which I then use in the page, like so:

```html
<img src={image} alt='A fun event'/>
```

...and it works fine like that. Image is resized and displayed properly.

BUT!

...when I add another width for a second image to be generated and potentially served, like this:

```js
import image from '$images/arrow-event-factory-1920x1200.jpg?width=480;960'
```

...it does not work anymore and I get the following vite error:

```bash
[vite] Internal server error: Cannot read property 'Symbol(image metadata)' of undefined
      at Object.getMetadata (/Users/rchrdnsh/Code/Svelte/Arrow-kit/node_modules/imagetools-core/dist/index.cjs:18:23)
      at /Users/rchrdnsh/Code/Svelte/Arrow-kit/node_modules/vite-imagetools/dist/index.cjs:87:75
      at call (/Users/rchrdnsh/Code/Svelte/Arrow-kit/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:49389:7)
      at next (/Users/rchrdnsh/Code/Svelte/Arrow-kit/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:49333:5)
      at Function.handle (/Users/rchrdnsh/Code/Svelte/Arrow-kit/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:49336:3)
      at Object.app [as middlewares] (/Users/rchrdnsh/Code/Svelte/Arrow-kit/node_modules/vite/dist/node/chunks/dep-5c642f9e.js:49201:37)
      at Server.<anonymous> (file:///Users/rchrdnsh/Code/Svelte/Arrow-kit/node_modules/@sveltejs/kit/dist/chunks/index.js:3276:14)
      at Server.emit (node:events:378:20)
      at Server.EventEmitter.emit (node:domain:470:12)
      at parserOnIncoming (node:_http_server:933:12) (x2)
```

...do you think I am doing something wrong in the code? Do you think it's something wrong with svelte and sveltekit? Do you think it's a vite issue? or maybe a bug in imagetools? I dunno where to start myself, but maybe you have a thought as to qhat might be going on?

Thanks!

**Comment by JonasKruckenberg** [comment]
This is very weird and definitely and issue with imagetools (`Symbol(image metadata)`) is used to track the generated metadata on the sharp instances. I will do some more investigating and get back to you once I know more!

**Comment by JonasKruckenberg** [comment]
Update:
I think I resolved the issue, it basically comes down to this:
imagetools exports a single string when it only generates a single image, but an array of images when it generates multiple images. So importing `'$images/arrow-event-factory-1920x1200.jpg?width=480'` works fine since it only generates a single string and svelte happily uses that as the images src attribute.
Once you generate multiple images however, the `image` variable suddenly holds an array of strings. Svelte however does not have a care in the world and joins the array(why though?) and uses that as the images source. This results in a request for an url like: 
```
http://localhost:3000/@imagetools/d37472e2c136ab5e7a6806ec591d386da5d40d1e,/@imagetools/fea063eb59b902f99d4a8dc11a3724c09ffbcc3a
```
which is obviously can not be fetched.

(You probably wanted to use `?srcset` with the import)

I added a more helpful error message for this problem though 👍

**Comment by rchrdnsh** [comment]
ok, so I tried this:

```js
import image from '$images/arrow-event-factory-1920x1200.jpg?width=480;960?srcset'
```

...and I'm still getting the same error...anything else I should be doing?

**Comment by JonasKruckenberg** [comment]
Huh, this is strange
`import image from '$images/arrow-event-factory-1920x1200.jpg?width=480;960&srcset'` (The second one) should work fine 🤔

**Comment by JonasKruckenberg** [comment]
So I did some testing, it seems like svelte is doing a bit behind-the-scenes magic with src and srcset attributes. For example the following:
```jsx
import images from '$images/arrow-event-factory-1920x1200.jpg?width=480;960'

<img src={images} />
```
will not work as noted above, but this:
```jsx
import images from '$images/arrow-event-factory-1920x1200.jpg?width=480;960&srcset'

<img src={images} />
```
will also not work. It has to be the correct combination of the srcset directive and the srcset attribute, so the following worked for me with svelte:
```jsx
import images from "./assets/image?width=480;960&srcset";

<img srcset={images} />
``

**Comment by JonasKruckenberg** [comment]
Closing this as I believe it is already fixed
