### ISSUE TITLE
Use the <Image> component

### ISSUE THREAD

**Issue by BeautyLips** [JonasKruckenberg/imagetools#728]
frameworks have become smaller, bundlers have become more efficient...

frameworks have become smaller, bundlers have become more efficient. Is this exactly true, and is it more effective? 2024, I can't do something like this 
UIIImage  :image-name="example.png"

and on the output get an image with srcset or picture?
can I use images dynamically?
no one does it like in your example - import in advance into the addresses component..

please provide example for

Image :name="example.png"

..in Image

optionsDefault = {
src: ?
srcset ?

return Image :src="?" :srcset="?"

**Comment by benmccann** [comment]
This is a low-level package meant to be used to help build such components. E.g. Svelte's `enhanced:img` is built on `vite-imagetools`: https://kit.svelte.dev/docs/images#sveltejs-enhanced-img

**Comment by BeautyLips** [comment]
thanks for the answer
