### ISSUE TITLE
Dosn't work if space in project folder name

### ISSUE THREAD

**Issue by r-bt** [JonasKruckenberg/imagetools#84]
Hey,

Firstly thanks for making this, it's great! It wasn't working for me first since there was a space in my project folder e.g. `Personal Site` which is then turned into `Personal%20Site` which sharp dosn't seem able to find giving me 

```
Input file is missing
```

Not sure if there's anything that can be done about this. It would have to take into account different operating systems. Anyway just wanted to make an issue to make this problem know and maybe help someone else trying to figure it out :)

**Comment by JonasKruckenberg** [comment]
Thanks for the report, this was a simple fix boiling down to a missing `decodeURIComponent`! Should be adressed in the latest versions `vite-imagetools@3.5.1` and `rollup-plugin-imagetools@2.1.1`!
