### ISSUE TITLE
Float/Double number passed to sharp

### ISSUE THREAD

**Issue by cxa** [JonasKruckenberg/imagetools#91]
I encountered errors that sharp not accepted width/height number such like 10.475xxxx. I think this two lines should use `Math.round` too:

https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/transforms/resize.ts#L82

https://github.com/JonasKruckenberg/imagetools/blob/main/packages/core/src/transforms/resize.ts#L87

(I intended to contribute but has no time to write tests, sorry).

**Comment by JonasKruckenberg** [comment]
You're right, I would just do the rounding at the end maybe?

> (I intended to contribute but has no time to write tests, sorry).

No problem ^^
